export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const CHECK_SESSION_START = 'CHECK_SESSION_START' 
export const CHECK_SESSION_SUCCESS = 'CHECK_SESSION_SUCCESS' 
export const CHECK_SESSION_FAIL = 'CHECK_SESSION_FAIL' 