version: '3'
services: 
    app:
        container_name: snipIt
        restart: always
        build: .
        ports:
            - '8000:8000'
        volumes:
            - .:/user/src/app
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"